import { writeFileSync } from "node:fs";
import { ownedCards } from "../seed/cards";
import { RARITIES, SERIES, buildCatalog } from "../seed/catalog-def";

// Emits the catalog (0002) and collection-import (0003) D1 migrations from the
// canonical catalog definition and the Sheet export. Run with `npm run seed:gen`.

const esc = (s: string) => s.replace(/'/g, "''");

const catalog = buildCatalog();
const validKeys = new Set(
  catalog.map((c) => `${c.series}|${c.character}|${c.rarity}`),
);

for (const card of ownedCards) {
  const key = `${card.series}|${card.character}|${card.rarity}`;
  if (!validKeys.has(key)) {
    throw new Error(`Owned card does not map to a catalog type: ${key}`);
  }
}

// No explicit BEGIN/COMMIT: D1 wraps each migration in its own transaction, and
// the remote D1 API rejects raw BEGIN TRANSACTION/COMMIT statements.
const catalogSql = [
  "-- 0002_seed_catalog.sql — generated by scripts/generate-seed.ts. DO NOT EDIT.",
  ...catalog.map(
    (c) =>
      `INSERT INTO card_catalog (series, character, rarity, sort_order) VALUES ('${esc(c.series)}', '${esc(c.character)}', '${c.rarity}', ${c.sortOrder});`,
  ),
  "",
].join("\n");
writeFileSync("migrations/0002_seed_catalog.sql", catalogSql);

const cardsSql = [
  "-- 0003_seed_cards.sql — generated by scripts/generate-seed.ts. DO NOT EDIT.",
  ...ownedCards.map(
    (c) =>
      `INSERT INTO cards (catalog_id, status, source) SELECT id, 'owned', '${c.source}' FROM card_catalog WHERE series='${esc(c.series)}' AND character='${esc(c.character)}' AND rarity='${c.rarity}';`,
  ),
  "",
].join("\n");
writeFileSync("migrations/0003_seed_cards.sql", cardsSql);

const bySeries: Record<string, number> = {};
const bySeriesRarity: Record<string, number> = {};
for (const c of ownedCards) {
  bySeries[c.series] = (bySeries[c.series] ?? 0) + 1;
  bySeriesRarity[`${c.series} ${c.rarity}`] =
    (bySeriesRarity[`${c.series} ${c.rarity}`] ?? 0) + 1;
}
const purchased = ownedCards.filter((c) => c.source === "purchase").length;
console.log(
  `catalog=${catalog.length} cards=${ownedCards.length} purchased=${purchased}`,
);
for (const s of SERIES) {
  const cells = RARITIES.map(
    (r) => `${r}=${bySeriesRarity[`${s} ${r}`] ?? 0}`,
  ).join(" ");
  console.log(`${s}: total=${bySeries[s] ?? 0} ${cells}`);
}
