import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { buildCatalogSyncMigration } from "./catalog-sync-migration";

const [inputFile, ...extra] = process.argv.slice(2);
if (!inputFile || extra.length > 0) {
  console.error("Usage: npm run catalog:sync -- <additions.json>");
  console.error(
    "D1 is authoritative; seed/catalog-def.ts is only the historical import.",
  );
  process.exit(1);
}

const statements = buildCatalogSyncMigration(
  JSON.parse(readFileSync(inputFile, "utf8")),
);

const nums = readdirSync("migrations")
  .map((f) => /^(\d{4})_/.exec(f)?.[1])
  .filter((n): n is string => Boolean(n))
  .map(Number);
const next = String((nums.length ? Math.max(...nums) : 0) + 1).padStart(4, "0");
const file = `migrations/${next}_sync_catalog.sql`;

const sql = [
  `-- ${next}_sync_catalog.sql — generated by scripts/sync-catalog.ts. DO NOT EDIT.`,
  "-- Explicit additions only; existing D1 metadata and catalog rows are preserved.",
  ...statements,
  "",
].join("\n");
writeFileSync(file, sql, { flag: "wx" });

console.log(`Wrote ${file}.`);
console.log(
  "Review and apply locally; verify catalog visibility and unchanged owned cards.",
);
console.log(
  "See docs/DEPLOY.md and the manage-card-catalog skill before production use.",
);
