import { readdirSync, writeFileSync } from "node:fs";
import { buildCatalog } from "../seed/catalog-def";

// Generates the next numbered migration that syncs the card_catalog table to
// seed/catalog-def.ts. Idempotent: inserts NEW card types and corrects
// sort_order for existing ones, via UPSERT on the UNIQUE(series,character,
// rarity) key. It never overwrites 0002/0003 and never touches the cards table,
// so the owner's imported collection is untouched. See the manage-card-catalog
// skill for the full procedure.

const esc = (s: string) => s.replace(/'/g, "''");

const nums = readdirSync("migrations")
  .map((f) => /^(\d{4})_/.exec(f)?.[1])
  .filter((n): n is string => Boolean(n))
  .map(Number);
const next = String((nums.length ? Math.max(...nums) : 0) + 1).padStart(4, "0");
const file = `migrations/${next}_sync_catalog.sql`;

const catalog = buildCatalog();
const sql = [
  `-- ${next}_sync_catalog.sql — generated by scripts/sync-catalog.ts. DO NOT EDIT.`,
  "-- Syncs card_catalog to seed/catalog-def.ts (additive + sort_order fix).",
  ...catalog.map(
    (c) =>
      `INSERT INTO card_catalog (series, character, rarity, sort_order) VALUES ('${esc(c.series)}', '${esc(c.character)}', '${c.rarity}', ${c.sortOrder}) ON CONFLICT(series, character, rarity) DO UPDATE SET sort_order = excluded.sort_order;`,
  ),
  "",
].join("\n");
writeFileSync(file, sql);

console.log(`Wrote ${file} (${catalog.length} card types).`);
console.log("Next: apply local + remote, run tests, then redeploy.");
console.log("See the manage-card-catalog skill for the full checklist.");
